coverage Test for only maxwell

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -115,6 +115,7 @@ before_script:
   # - if [ -n "${DO_CODE_COVERAGE}" ]; then
   - if [ "$CI_PIPELINE_SOURCE" == "push" ]; then
       export CODE_COVERAGE=True;
+      if [ ! -d "Coverage" ]; then mkdir Coverage ; fi ;
       echo "DO_CODE_COVERAGE activated. Setting CMAKE_Fortran_FLAGS to --coverage";
       COVERAGE_CMAKE_FLAG="-DCMAKE_Fortran_FLAGS=\"--coverage\"";
     else
@@ -166,6 +167,11 @@ stages:
   paths: [reggie]
   policy: pull
 
+.coverage_cache: &coverage_cache
+  key: "${CI_COMMIT_REF_SLUG}-coverage"
+  paths: [Coverage]
+  policy: pull-push
+
 # ----------------------------------------------------------------------------------------------------------------------------------------------------
 # Defaults for the standard maxwell tests (utilizing "extends" to merge the other "artifacts" options with the specific path)
 .defaults: &defaults
@@ -178,6 +184,7 @@ stages:
     - key: "${CI_COMMIT_REF_SLUG}"
       paths: [build]
       policy: pull
+    - *coverage_cache
 
 .defaults_checkin: &defaults_checkin
   <<: *defaults
@@ -210,6 +217,7 @@ stages:
     - key: "${CI_COMMIT_REF_SLUG}-MAX"
       paths: [build_maxwell_only]
       policy: pull
+    - *coverage_cache
   rules:
     - if: '$DO_CHECKIN'
     - if: '$CI_PIPELINE_SOURCE == "push"'
@@ -1436,22 +1444,26 @@ reggie_code_coverage:
   stage: reggie_code_coverage
   script:
     - echo "Generating combined coverage report..."
-    - mkdir -p Coverage
+    - mkdir -p Coverage/cobertura
     # combine coverage reports of all builds and runs
-    - gcovr --root /src --add-tracefile "build*/output_dir/single_reports/*.json" --xml Coverage/coverage.xml --print-summary
+    - ls -la
+    - ls -la build* || echo "not found"
+    - ls -la Coverage || echo "not found"
+    - gcovr --root /src --add-tracefile "Coverage/*.json" --xml Coverage/cobertura/coverage.xml --print-summary
+    - ls -la Coverage/cobertura || echo "not found"
     # split coverage.xml file into smaller files since gitlab has a limit of 10MB per file, but seems to have no limit for number of files
-    - python tools/Coverage/split-xml-by-package.py Coverage/coverage.xml Coverage
+    - python tools/Coverage/split-xml-by-package.py Coverage/cobertura/coverage.xml Coverage/cobertura
   # regex expression the retrieve coverage percentage
   coverage: '/lines:\s+(\d+(\.\d+)?)%/'
   artifacts:
     paths:
-      - Coverage/coverage.xml
+      - Coverage/cobertura/coverage.xml
     expire_in: 1 week
     reports:
       coverage_report:
         coverage_format: cobertura
         # use smaller files for gitlab artifacts
-        path: Coverage/cobertura*.xml
+        path: Coverage/cobertura/cobertura*.xml
   rules:
     # //TODO: remove checkin and push after testing
     - if: '$DO_CHECKIN'
